### ISSUE TITLE
The status bar is painted in the same color as toolbar

### ISSUE THREAD

**Issue by Lobynya** [icerockdev/moko-widgets#102]
If Toolbar white, then status bar turns white too, and the text on it becomes unreadable

**Comment by Alex009** [comment]
old implementation of status bar coloring was with bugs, so now it disabled #106

**Comment by Alex009** [comment]
in any screen or in `Application` class you can:
```
override val androidStatusBarColor: Color? = Color(0xFFFFFFFF)
override val isLightStatusBar: Boolean? = true
```

`androidStatusBarColor` - change status bar color on android only
`isLightStatusBar` - change content color of status bar. if your status bar is light colors - set true and content will be dark. 

null values use default system settings

**Comment by Alex009** [comment]
merged
