### ISSUE TITLE
Set content resistance for wrapContent size on iOS

### ISSUE THREAD

**Issue by Dorofeev** [icerockdev/moko-widgets#117]
val valueView = +text(
                    category = valueCategory,
                    size = WidgetSize.WrapContent,
                    text = data.map { it.value }
                )

                val titleView = +text(
                    category = titleCategory,
                    size = WidgetSize.WrapContent,
                    text = data.map { it.title }
                )
                constraints {
                    titleView leftToLeft root offset 16
                    titleView topToTop root offset 8
                    titleView bottomToBottom root

                    valueView leftToRight  titleView offset 16

                    valueView rightToRight root offset 16
                    valueView topToTop root offset 8
                    valueView bottomToBottom root
                }

I got this constraint in widget and in result if valueView have big content its compress titleView, and I want to prevent it 

<img width="363" alt="Снимок экрана 2020-02-18 в 10 38 44" src="https://user-images.githubusercontent.com/701307/74701895-e31b0100-523a-11ea-933d-86fc3a8fc3c8.png">

**Comment by Alex009** [comment]
merged
