### ISSUE TITLE
Incorrect fontStyle in labelTextStyle and textStyle on InputWidget

### ISSUE THREAD

**Issue by Anafemest** [icerockdev/moko-widgets#12]
If you specify the FontStyle.BOLD for the textStyle, then it will apply to the text and label.
If you specify the FontStyle.BOLD for the labelTextStyle - it does not apply anywhere

![image](https://user-images.githubusercontent.com/20812586/72242911-11466900-361d-11ea-8847-0f8d5bbc85e3.png)
![image](https://user-images.githubusercontent.com/20812586/72243702-2e7c3700-361f-11ea-92ed-ae0009796cc2.png)

**Comment by Alex009** [comment]
fixed and merged
