### ISSUE TITLE
Add customization to SystemTabsViewFactory

### ISSUE THREAD

**Issue by Dorofeev** [icerockdev/moko-widgets#131]
What need to customize: 
- tintColor
- padding for iOS 
- textStyle for Android (selected, unselected)
- add shadow

for example:
<img width="674" alt="Снимок экрана 2020-02-20 в 15 35 12" src="https://user-images.githubusercontent.com/701307/74915330-9d0a9c80-53f6-11ea-95f0-eef2aeacd12e.png">

<img width="530" alt="Снимок экрана 2020-02-20 в 15 33 35" src="https://user-images.githubusercontent.com/701307/74915255-7e0c0a80-53f6-11ea-8dbe-c7094e7618a3.png">

**Comment by Alex009** [comment]
merged.

config to implement attached sample:
```
SystemTabsViewFactory(
    tabsTintColor = Color(0xD20C0AFF),
    tabsPadding = platformSpecific(android = null, ios = PaddingValues(padding = 16f)),
    selectedTitleColor = Color(platformSpecific(android = 0x151515FF, ios = 0xFFFFFFFF)),
    normalTitleColor = platformSpecific(android = Color(0x15151599), ios = null)
)
```
