### ISSUE TITLE
SystemImageViewFactory create ImageWidget with different size on ios and android

### ISSUE THREAD

**Issue by Lobynya** [icerockdev/moko-widgets#162]
In case, when ImageWidget has 
size=WidgetSize.WidthAsParentHeightWrapContent 
and  
scaleType = ImageWidget.ScaleType.FILL 
then SystemImageViewFactory create widget with different size

android:
![Screenshot_20200227-150153](https://user-images.githubusercontent.com/26733767/75424531-66430200-5973-11ea-878d-5b9cf3d31554.jpg)
ios:
![Screenshot 2020-02-27 at 14 59 03](https://user-images.githubusercontent.com/26733767/75424550-722ec400-5973-11ea-8589-8fb0b4309f93.png)

**Comment by Alex009** [comment]
fix merged
