### ISSUE TITLE
ConstraintLayout has an ripple effect. Focus out dont focus input field

### ISSUE THREAD

**Issue by Anafemest** [icerockdev/moko-widgets#18]
When val isDismissKeyboardOnTap: Boolean = true
If you focus the background of the application (using the physical keyboard and the tab button)
then the background becomes clickable and draws the ripple effect
![12121](https://user-images.githubusercontent.com/20812586/72324961-abbab100-36de-11ea-9d72-eac8ea3f4cba.gif)

The field does not lose focus

1. I tap on the password field
2. the field becomes in focus
3. keyboard opens
4. I tap on an empty place outside the field
5. the keyboard is retracted
6. the focus does not disappear from the field, the field is still in focus

**Comment by Alex009** [comment]
merged
