### ISSUE TITLE
WebView Widget not loaded on Android

### ISSUE THREAD

**Issue by kovalandrew** [icerockdev/moko-widgets#192]
Can't load url in webView with Android for URL https://alpha.virtualvi.be/ru/o/biobeauty/1?api_token=zmCfJkjtiDWINXhY. It is show me error `"Uncaught TypeError: Cannot read property 'getItem' of null", source: https://alpha.virtualvi.be/js/app.02e39ac6.js` but on iOS and web works fine

**Comment by Alex009** [comment]
merged
