### ISSUE TITLE
Increase FloatingLabelInputView tap area (iOS)

### ISSUE THREAD

**Issue by Dorofeev** [icerockdev/moko-widgets#219]
<img width="768" alt="Снимок экрана 2020-04-09 в 11 13 29" src="https://user-images.githubusercontent.com/701307/78857303-36e3e280-7a53-11ea-9222-8561129b52b5.png">

Input field become active only when you click exactly on UItextField. I think it should become active after tap on any place of sky floating input view.

**Comment by Alex009** [comment]
merged
