### ISSUE TITLE
XCode build failed

### ISSUE THREAD

**Issue by Diy2210** [icerockdev/moko-widgets#254]
Hi, I run **pod install**  but console show **Failure: Build failed** 
![Снимок экрана 2020-07-02 в 12 48 41](https://user-images.githubusercontent.com/9552501/86344426-f0bdaa00-bc62-11ea-8711-d58c6608c5b1.png)
But **Pod installation is complete!**

And them Xcode show build failed too:
![Снимок экрана 2020-07-02 в 12 48 09](https://user-images.githubusercontent.com/9552501/86344616-2498cf80-bc63-11ea-8a34-ccafc72a4c14.png)
![Снимок экрана 2020-07-02 в 12 48 53](https://user-images.githubusercontent.com/9552501/86344634-2bbfdd80-bc63-11ea-880f-b08799c6acbc.png)

How I fix it?

**Comment by Diy2210** [comment]
I use java:
![Снимок экрана 2020-07-03 в 10 30 09](https://user-images.githubusercontent.com/9552501/86456016-22e60f00-bd2a-11ea-8ff9-954f50d9c162.png)

And project:
![Снимок экрана 2020-07-03 в 10 30 27](https://user-images.githubusercontent.com/9552501/86456056-2f6a6780-bd2a-11ea-9d09-3ac9f28b4c2f.png)

I try clean cache gradle and pod install again, but I get error too:
**ERROR: Could not initialize class org.codehaus.groovy.runtime.InvokerHelper**
![Снимок экрана 2020-07-03 в 12 42 00](https://user-images.githubusercontent.com/9552501/86456348-9ab43980-bd2a-11ea-9122-493de4035d0d.png)

**Comment by Alex009** [comment]
Did I understand correctly that the error occurs in the terminal, but not in IDEA? if you build from IDEA - all work correctly?
your case not our project related - it about gradle usage. here details https://github.com/gradle/gradle/issues/12599
Please try to run `./gradlew -version` from terminal to check what JDK used by gradle
Also more info about problem here - https://github.com/gradle/gradle/issues/10248

**Comment by Diy2210** [comment]
> Did I understand correctly that the error occurs in the terminal, but not in IDEA? if you build from IDEA - all work correctly?
> your case not our project related - it about gradle usage. here details [gradle/gradle#12599](https://github.com/gradle/gradle/issues/12599)
> Please try to run `./gradlew -version` from terminal to check what JDK used by gradle
> Also more info about problem here - [gradle/gradle#10248](https://github.com/gradle/gradle/issues/10248)

Error occurs in the **terminal** when I try **pod install**
My **./gradlew -version** dont use. I use the **built-in IntelliJ gradle**. 
![Снимок экрана 2020-07-07 в 09 41 24](https://user-images.githubusercontent.com/9552501/86729769-7e6c1180-c036-11ea-88d6-6e424eff4de6.png)

I try use **JAVA 8,9,10,11,12,13** but pod install print error.

**Comment by Alex009** [comment]
in your project root contained `./gradlew`, which used by `pod install` to compile shared module. call `./gradlew -version` not from `~` but from your project root.

**Comment by Diy2210** [comment]
> in your project root contained `./gradlew`, which used by `pod install` to compile shared module. call `./gradlew -version` not from `~` but from your project root.

Oh, I get it=)

![Снимок экрана 2020-07-07 в 10 25 53](https://user-images.githubusercontent.com/9552501/86736646-5d0e2400-c03c-11ea-8f7f-06e4ea974102.png)

**Comment by Alex009** [comment]
to fix your problem you should change default JVM, which used by gradle, to 1.8

**Comment by Diy2210** [comment]
> to fix your problem you should change default JVM, which used by gradle, to 1.8

I change **JVM to 1.8** and **_Pod installation complete!,_** but **XCode print error** again!
Gradle:
![Снимок экрана 2020-07-13 в 14 56 08](https://user-images.githubusercontent.com/9552501/87302061-60604e80-c519-11ea-85fd-30c577d04f83.png)

Xcode:
![Снимок экрана 2020-07-13 в 14 56 58](https://user-images.githubusercontent.com/9552501/87302076-66eec600-c519-11ea-87e3-ec252f5597f4.png)

**Comment by Alex009** [comment]
congratulations on the progress :)
i see xcode print same error as later. i think xcode continue use invalid version of jvm in runs...you can try change build script here:
https://github.com/Diy2210/compoza.lite2.moko/blob/master/mpp-library/MultiPlatformLibrary.podspec#L33
for tests just comment 33 line and add 
`"$MPP_PROJECT_ROOT/../gradlew" -version`
after it do `pod install` and try to build from xcode - in logs of xcode you got used by xcode version jvm. after it try to change jvm to 1.8...and when gradle output jvm 1.8 from xcode build - rollback change in 33 line of podspec

**Comment by Diy2210** [comment]
**WOW, its works, if use JVM 1.8, and change 33 line in MultiPlatformLibrary.podspec file! Cool, tnx! I'm happy now!**
![2020-07-15](https://user-images.githubusercontent.com/9552501/87649768-65134580-c759-11ea-976c-a9668a95ad5f.png)
![2020-07-15-1](https://user-images.githubusercontent.com/9552501/87649781-680e3600-c759-11ea-8580-358517b358b7.png)

**Comment by Alex009** [comment]
@Diy2210 problem solved? we can close issue?
