### ISSUE TITLE
Help add items to ListWidget

### ISSUE THREAD

**Issue by Diy2210** [icerockdev/moko-widgets#256]
Hi, I try add **items to ListWidget**, type arrayOf. How can I do this?

My Array:
![Снимок экрана 2020-07-06 в 15 55 35](https://user-images.githubusercontent.com/9552501/86595475-757d3080-bfa1-11ea-9db7-f8f4f80a0c55.png)

My Live Data:
![Снимок экрана 2020-07-06 в 15 57 10](https://user-images.githubusercontent.com/9552501/86595518-84fc7980-bfa1-11ea-9495-6bd09259de67.png)

My ListWidget:
![Снимок экрана 2020-07-06 в 15 56 52](https://user-images.githubusercontent.com/9552501/86595540-8f1e7800-bfa1-11ea-87f7-959d06902c88.png)

**Comment by Alex009** [comment]
just change `arrayOf` to `listOf` and use List instead of Array.
or do `viewModel.diskInfoArray.map { it.toList() }` to convert Array into List

**Comment by Diy2210** [comment]
I try convert Array to List, but my **MutableLiveData** type **Model** and ListWidget work only with **TableUnitItem**. I need **_convert_** **MutableLiveData** to **TableUnitItem**?

![Снимок экрана 2020-07-06 в 16 58 29](https://user-images.githubusercontent.com/9552501/86605951-0529db80-bfb0-11ea-95be-4dae6da6510d.png)

![Снимок экрана 2020-07-06 в 16 58 15](https://user-images.githubusercontent.com/9552501/86605960-08bd6280-bfb0-11ea-860e-6fd12bfd5651.png)

**Comment by Alex009** [comment]
oh, yes. you should map your model into TableUnitItem.
For example you can use standard unit items - https://github.com/icerockdev/moko-units/blob/master/units-basic/src/commonMain/kotlin/dev/icerock/moko/units/basic/table/BasicTableUnitItem.kt
or you can create WidgetTableUnitItem just like here - https://github.com/icerockdev/moko-widgets/blob/master/sample/mpp-library/src/commonMain/kotlin/com/icerockdev/library/units/UserUnitWidget.kt#L94

**Comment by Diy2210** [comment]
Thanks, I got it. All works!
