### ISSUE TITLE
Help check value and set image to ImageWidget

### ISSUE THREAD

**Issue by Diy2210** [icerockdev/moko-widgets#257]
Hi, how I can check value in **_override fun createWidget_** like **if/else** or something like that and select one or another image.

I use **List Widget** and **Table Units**:

My ListWidget:
![Снимок экрана 2020-07-07 в 12 58 53](https://user-images.githubusercontent.com/9552501/86766071-b2553000-c052-11ea-9516-ed1cb69c50da.png)

Fun Table Units:
![Снимок экрана 2020-07-07 в 12 59 01](https://user-images.githubusercontent.com/9552501/86766124-c26d0f80-c052-11ea-8d4c-b0dc81c27e82.png)

My class Unit Items where I make image:
![Снимок экрана 2020-07-07 в 12 59 20](https://user-images.githubusercontent.com/9552501/86766190-d9abfd00-c052-11ea-8d2d-8327aee21acd.png)

Result:
![Снимок экрана 2020-07-07 в 12 59 39](https://user-images.githubusercontent.com/9552501/86766210-e3356500-c052-11ea-91cc-6b154614b4b6.png)

**Comment by Alex009** [comment]
@Diy2210 widget creation called only on create of Table item, but when UITableView/RecyclerView reuse already created item you got notification in `data: LiveData<StatusModel>`, so you should use not `image  = const(image)` but `image = data.map { .... }` where in map you convert `StatusModel` to correct `Image`

**Comment by Diy2210** [comment]
**Cool!!! All works! TNX!!!**

upd code:
![Снимок экрана 2020-07-07 в 16 51 54](https://user-images.githubusercontent.com/9552501/86791466-3b2f9400-c072-11ea-9eec-3ffe112f097e.png)

result:
![Снимок экрана 2020-07-07 в 16 51 31](https://user-images.githubusercontent.com/9552501/86791483-41257500-c072-11ea-9f78-0d72d1dc2d93.png)

**Comment by Alex009** [comment]
@Diy2210 instead of `data.value` use `it` - already passed into lambda

**Comment by Diy2210** [comment]
> @Diy2210 instead of `data.value` use `it` - already passed into lambda

**_OK, TNX again!!!_**
