### ISSUE TITLE
Help set formatted value to TextWidget

### ISSUE THREAD

**Issue by Diy2210** [icerockdev/moko-widgets#258]
Hi, I try convert value to byte size to Gb and set to TextWidget in UnitItem. But in block
**_text = data.map { ... }_** I get an error. 
And I don't understand how add in this block value + "String" like 
**_text = data.map { it.total.desc() + "Gb" as StringDesc() }_** **Always return Error**.
In Android I use **android.text.format.Formatter.formatShortFileSize** and all works.

**Value("total" in Kb):**
![Снимок экрана 2020-07-08 в 12 27 57](https://user-images.githubusercontent.com/9552501/86903086-8780df80-c117-11ea-9f68-22e3a1525f9f.png)

**My List:**
![Снимок экрана 2020-07-08 в 12 29 26](https://user-images.githubusercontent.com/9552501/86903190-aaab8f00-c117-11ea-8ba4-85fbc324beca.png)

**My fun TableUnits:**
![Снимок экрана 2020-07-08 в 12 29 37](https://user-images.githubusercontent.com/9552501/86903223-b5662400-c117-11ea-8a54-b198296debce.png)

Class unit items where I create TextWidget:
![Снимок экрана 2020-07-08 в 12 28 42](https://user-images.githubusercontent.com/9552501/86903322-da5a9700-c117-11ea-9769-a4796c7ada4a.png)

Convert fun to Mb/Gb:
![Снимок экрана 2020-07-08 в 12 28 20](https://user-images.githubusercontent.com/9552501/86903372-eb0b0d00-c117-11ea-8dcf-e865105cd939.png)

**Comment by Dorofeev** [comment]
If I understand correctly, what are you trying to do, you can use string template feature as shown below
```
text = data.map {
    if (it.total.isNotEmpty()) {
        "${bytesToGB(it.total.toLong())} Gb".desc()
    } else {
        it.total.desc()
    }
}
```

**Comment by Diy2210** [comment]
> If I understand correctly, what are you trying to do, you can use string template feature as shown below
> 
> ```
> text = data.map {
>     if (it.total.isNotEmpty()) {
>         "${bytesToGB(it.total.toLong())} Gb".desc()
>     } else {
>         it.total.desc()
>     }
> }
> ```

**I try it, but dont work, error returns!**

**Comment by Dorofeev** [comment]
Can you provide more information about what kind of error is it?

**Comment by Tetraquark** [comment]
@Diy2210 Try to use this construction:

```kotlin
text = data.map {
    if (it.total.isNotEmpty()) {
        "${bytesToGB(it.total.toLong())} Gb".desc()
    } else {
        it.total.desc()
    } as StringDesc
}
```

**Comment by Diy2210** [comment]
> Try to use this construction:

Oh, **dont work too**

Print error:
![Снимок экрана 2020-07-08 в 16 25 03](https://user-images.githubusercontent.com/9552501/86924189-cd4da000-c137-11ea-9b41-9efc5b0cfcff.png)

Error:
![Снимок экрана 2020-07-08 в 16 24 38](https://user-images.githubusercontent.com/9552501/86924237-dc345280-c137-11ea-964b-d65508e65be2.png)

My Mutable Live Data:
![Снимок экрана 2020-07-08 в 16 25 28](https://user-images.githubusercontent.com/9552501/86924347-01c15c00-c138-11ea-97ba-b4036cc3f3f6.png)
![Снимок экрана 2020-07-08 в 16 27 49](https://user-images.githubusercontent.com/9552501/86924373-09810080-c138-11ea-800f-1075bd4c2f36.png)

Save Value to Data:
![Снимок экрана 2020-07-08 в 16 27 56](https://user-images.githubusercontent.com/9552501/86924418-1998e000-c138-11ea-85d5-ab77b95e69c2.png)

**Comment by Dorofeev** [comment]
Looks like problem is that `it.total` is not a number. Something like this should resolve problem.
```
text = data.map {
    val longTotal = it.total.toLongOrNull()
    if (longTotal != null) {
        "${bytesToGb(longTotal)} Gb".desc()
    } else {
        it.total.desc()
    } as StringDesc
}
```

**Comment by Diy2210** [comment]
> Something like this should resolve problem.

**Yeah, its work! Tnx bro!**
![Снимок экрана 2020-07-08 в 17 04 47](https://user-images.githubusercontent.com/9552501/86928459-3b489600-c13d-11ea-9534-5ee1594495c7.png)

**Comment by Diy2210** [comment]
And one more question, I try get percents **_(free * 100) / total_**, but an **error is returned**.

![Снимок экрана 2020-07-09 в 10 42 59](https://user-images.githubusercontent.com/9552501/87011922-3c2b0780-c1d1-11ea-9f12-af2910ac76b3.png)

![Снимок экрана 2020-07-09 в 10 43 15](https://user-images.githubusercontent.com/9552501/87012019-5b299980-c1d1-11ea-80f5-c6d24b76e454.png)

**Comment by Dorofeev** [comment]
`longFree!!` will cause crash if it is `null`, you should move it inside if statement
```
if (longFree != null && longTotal != null) {
   val freePerCents = (longFree * 100) / longTotal
   "${freePerCents} %".desc()
}
```
You can read more about null-safety in Kotlin documentation https://kotlinlang.org/docs/reference/null-safety.html

**Comment by Diy2210** [comment]
**I get it, all works goog, tnx again!**
![Снимок экрана 2020-07-09 в 11 03 51](https://user-images.githubusercontent.com/9552501/87013917-0cc9ca00-c1d4-11ea-8e69-9bdd3a289c9d.png)
