### ISSUE TITLE
Help add MutableLiveData from ListWidget

### ISSUE THREAD

**Issue by Diy2210** [icerockdev/moko-widgets#264]
Hi, I try add MutableLiveData use Database, but I don't understand how.

My List in database:
![Снимок экрана 2020-07-20 в 11 52 56](https://user-images.githubusercontent.com/9552501/87919634-c3556680-ca80-11ea-8828-09ca2cedbe39.png)

Database class:
![Снимок экрана 2020-07-20 в 11 54 58](https://user-images.githubusercontent.com/9552501/87919663-cea89200-ca80-11ea-8a4d-c0becd7a012d.png)

My old MutableLiveData in ViewModelClass:
![Снимок экрана 2020-07-20 в 11 57 35](https://user-images.githubusercontent.com/9552501/87919753-eed85100-ca80-11ea-8f36-0b4bec59de42.png)

UnitItem class:
![Снимок экрана 2020-07-20 в 11 54 36](https://user-images.githubusercontent.com/9552501/87919821-08799880-ca81-11ea-98f7-1ead8424ce6f.png)

And use in ListWidget:
![Снимок экрана 2020-07-20 в 11 55 31](https://user-images.githubusercontent.com/9552501/87919887-20e9b300-ca81-11ea-94ae-1a6e62358dcc.png)
![Снимок экрана 2020-07-20 в 11 55 41](https://user-images.githubusercontent.com/9552501/87919906-28a95780-ca81-11ea-8559-aacb7eec9e4a.png)

**Comment by Diy2210** [comment]
DONE!
I refactor code. 
MutableLiveData:
![Снимок экрана 2020-07-20 в 15 32 53](https://user-images.githubusercontent.com/9552501/87938216-e262f100-ca9e-11ea-9444-763ac0950981.png)

Table Units:
![Снимок экрана 2020-07-20 в 15 33 19](https://user-images.githubusercontent.com/9552501/87938247-ee4eb300-ca9e-11ea-80c9-6848f95a7ace.png)

 Result:
![Screenshot_1595248317](https://user-images.githubusercontent.com/9552501/87938253-f4449400-ca9e-11ea-8591-b4f6111f1055.png)

But I have one more question, how implement **auto add new items from ListWidget**? Now to see the new entry in the list I need to restart the application **like notifyDataSetChanged() in JAVA =)**

**Comment by Alex009** [comment]
@Diy2210 to notify changes you should use livedata's `value` field to change value.
`_servers.value = myNewList` and all will be updated. LiveData it's reactive data holder, all widgets subscribed to livedata and update automatically when value of livedata was changed

**Comment by Diy2210** [comment]
> @Diy2210 to notify changes you should use livedata's `value` field to change value.
> `_servers.value = myNewList` and all will be updated. LiveData it's reactive data holder, all widgets subscribed to livedata and update automatically when value of livedata was changed

I do not quite understand, you can use my example plz?

My ViewModel:
![Снимок экрана 2020-07-21 в 16 18 48](https://user-images.githubusercontent.com/9552501/88059849-15c08100-cb6e-11ea-84fb-9ea9029ad3c7.png)

ListWidget:
![Снимок экрана 2020-07-21 в 16 19 04](https://user-images.githubusercontent.com/9552501/88059882-2113ac80-cb6e-11ea-9328-d05d63c0295d.png)

TableUnits:
![Снимок экрана 2020-07-21 в 16 19 15](https://user-images.githubusercontent.com/9552501/88059903-2c66d800-cb6e-11ea-8442-392122a79cd6.png)

**Comment by Diy2210** [comment]
I try add fun reload list items, but it not works:

![Снимок экрана 2020-07-22 в 14 20 02](https://user-images.githubusercontent.com/9552501/88170519-80cd8e80-cc26-11ea-8dd6-2de151819af9.png)

![Снимок экрана 2020-07-22 в 14 20 14](https://user-images.githubusercontent.com/9552501/88170527-84f9ac00-cc26-11ea-9204-b32027526b68.png)

**Comment by Diy2210** [comment]
I get it, gust add **_servers.value = list** to **fun reload()**. Now all be updated! **Tnx!**
