### ISSUE TITLE
How to add multiple arguments to Route

### ISSUE THREAD

**Issue by Diy2210** [icerockdev/moko-widgets#265]
How to add **multiple arguments to Route<?, ?, ?>** if Route have one arg?

![Снимок экрана 2020-07-20 в 17 47 45](https://user-images.githubusercontent.com/9552501/87952084-0c71de80-cab2-11ea-8ee1-be1cf7371e57.png)

![Снимок экрана 2020-07-20 в 17 51 29](https://user-images.githubusercontent.com/9552501/87952095-11cf2900-cab2-11ea-8a03-47b925bb11a1.png)

![Снимок экрана 2020-07-20 в 17 51 37](https://user-images.githubusercontent.com/9552501/87952111-1693dd00-cab2-11ea-90a0-b555fb770a26.png)

**Comment by Alex009** [comment]
@Diy2210 just build @Parcelable class for argument data.
```
@Parcelize
data class Arg(val title: String, val url: String, val token: String): Parcelable
```

**Comment by Diy2210** [comment]
> @Diy2210 just build @parcelable class for argument data.
> 
> ```
> @Parcelize
> data class Arg(val title: String, val url: String, val token: String): Parcelable
> ```

I build **Parcelize**, but I get error in App.class:
![Снимок экрана 2020-07-20 в 18 14 40](https://user-images.githubusercontent.com/9552501/87954472-16e1a780-cab5-11ea-9ee4-36732abfe361.png)

![Снимок экрана 2020-07-20 в 18 14 24](https://user-images.githubusercontent.com/9552501/87954486-1ba65b80-cab5-11ea-9e49-143c43ac6f4e.png)

![Снимок экрана 2020-07-20 в 18 13 13](https://user-images.githubusercontent.com/9552501/87954500-1fd27900-cab5-11ea-9a5e-e30abbb55b3b.png)

![Снимок экрана 2020-07-20 в 18 14 00](https://user-images.githubusercontent.com/9552501/87954553-337ddf80-cab5-11ea-875b-2492d0069f39.png)

![Снимок экрана 2020-07-20 в 18 14 13](https://user-images.githubusercontent.com/9552501/87954574-38db2a00-cab5-11ea-9c44-f1db2c074ffd.png)

**Comment by Alex009** [comment]
@Diy2210 your route require `Arg` type of argument...here sample of argument pass - https://github.com/icerockdev/moko-widgets/blob/d454975028bb036a74fc0af7230dde49643be802/sample/mpp-library/src/commonMain/kotlin/App.kt#L363

**Comment by Diy2210** [comment]
> @Diy2210 your route require `Arg` type of argument...here sample of argument pass -
> 
> https://github.com/icerockdev/moko-widgets/blob/d454975028bb036a74fc0af7230dde49643be802/sample/mpp-library/src/commonMain/kotlin/App.kt#L363

**Tnx again!**
