### ISSUE TITLE
ListWidget on iOS dont work

### ISSUE THREAD

**Issue by Diy2210** [icerockdev/moko-widgets#268]
Hi, I generate iOS app and ListWidget dont show items. In Android all works I dond understand why.

My ListWidget:
![Снимок экрана 2020-07-23 в 14 42 42](https://user-images.githubusercontent.com/9552501/88283390-f18eac80-ccf3-11ea-8a08-f18b05698d17.png)

TableUnits:
![Снимок экрана 2020-07-23 в 14 42 50](https://user-images.githubusercontent.com/9552501/88283437-08350380-ccf4-11ea-9ce0-27a8a05bcf47.png)

UnitItem class:
![Снимок экрана 2020-07-23 в 14 43 34](https://user-images.githubusercontent.com/9552501/88283406-f94e5100-ccf3-11ea-99bd-1f358c40f893.png)

Value in Xcode:
![Снимок экрана 2020-07-23 в 14 44 29](https://user-images.githubusercontent.com/9552501/88283462-16831f80-ccf4-11ea-89df-01657f3f40ac.png)

Result iOS:
![Simulator Screen Shot - iPhone SE (2nd generation) - 2020-07-23 at 14 44 33](https://user-images.githubusercontent.com/9552501/88283484-1edb5a80-ccf4-11ea-9c6e-fc2340f6f456.png)

Android:
![Screenshot_1595504680](https://user-images.githubusercontent.com/9552501/88283492-26026880-ccf4-11ea-8c48-0cb3594fbd2c.png)

And round button on iOS is strange =)

**Comment by Dorofeev** [comment]
And about button, cornerRadius should be half of button height/width

**Comment by Diy2210** [comment]
Oh yeah I fix it, TNX! Left to fix item size and will be complete.
![Simulator Screen Shot - iPhone SE (2nd generation) - 2020-07-23 at 17 38 59](https://user-images.githubusercontent.com/9552501/88299806-7507c800-cd0b-11ea-8ed0-86f7cfe28f15.png)
