### ISSUE TITLE
Implement View.Gone/Visible from Widgets

### ISSUE THREAD

**Issue by Diy2210** [icerockdev/moko-widgets#269]
Hi, how implement **View.Gone/Visible** like native UI from **ImageWidget** if **value = null**? 

Image:
![Снимок экрана 2020-07-24 в 14 38 14](https://user-images.githubusercontent.com/9552501/88387711-bfe11880-cdbb-11ea-8de1-f17449eeb80c.png)

Value:
![Снимок экрана 2020-07-24 в 14 38 33](https://user-images.githubusercontent.com/9552501/88387766-dd15e700-cdbb-11ea-9611-4fe161877045.png)

If value(updates) == 0, image warning GONE:
![Снимок экрана 2020-07-24 в 14 30 34](https://user-images.githubusercontent.com/9552501/88387778-e43cf500-cdbb-11ea-99f7-af8b17f91415.png)

**Comment by Dorofeev** [comment]
You can use [VisibilityWidget](https://github.com/icerockdev/moko-widgets/blob/7d46c359ec3a5854a0feae577c18fef9dfeeccee/widgets/src/commonMain/kotlin/dev/icerock/moko/widgets/VisibilityWidget.kt) for that
