### ISSUE TITLE
Button widget with text and icon

### ISSUE THREAD

**Issue by kovalandrew** [icerockdev/moko-widgets#27]
We have currently two ways for style button:
1. Set text title
2. Set image for button

Need to add ability for set both of them, like this:
![Снимок экрана 2020-01-27 в 12 20 25](https://user-images.githubusercontent.com/11803725/73151811-7743ed80-40ff-11ea-8cbb-165d1fb6f04c.png)

Need to create new Factory with setup:
1. icon resource
2. icon alignment (left/middle/right)
3. text value
4. text alignment
5. Background color or gradient fill

**Comment by Alex009** [comment]
merged

**Comment by Alex009** [comment]
factory API is:
```
expect class ButtonWithIconViewFactory(
    background: StateBackground? = null,
    textStyle: TextStyle? = null,
    isAllCaps: Boolean? = null,
    padding: PaddingValues? = null,
    margins: MarginValues? = null,
    androidElevationEnabled: Boolean? = null,
    iconGravity: IconGravity? = null,
    iconPadding: Float? = null,
    icon: ImageResource
) : ViewFactory<ButtonWidget<out WidgetSize>>

enum class IconGravity {
    START,
    END,
    TEXT_START,
    TEXT_END
}
```
