### ISSUE TITLE
Help fix constraint elements

### ISSUE THREAD

**Issue by Diy2210** [icerockdev/moko-widgets#270]
How fix it?

Android:
![Снимок экрана 2020-07-24 в 15 42 11](https://user-images.githubusercontent.com/9552501/88392672-1868e380-cdc5-11ea-8d89-6f4dde051a8a.png)

iOS:
![Simulator Screen Shot - iPhone SE (2nd generation) - 2020-07-24 at 15 46 51](https://user-images.githubusercontent.com/9552501/88392692-21f24b80-cdc5-11ea-8707-4bd1c9f0b388.png)

Constraint Item:
![Снимок экрана 2020-07-24 в 15 46 19](https://user-images.githubusercontent.com/9552501/88392808-4cdc9f80-cdc5-11ea-917e-3bd73055ae27.png)

Constraint:
![Снимок экрана 2020-07-24 в 15 46 34](https://user-images.githubusercontent.com/9552501/88392761-3f271a00-cdc5-11ea-8a8f-4da8356c9de5.png)

And one more question why button style in iOS another? How fix it too?
Left iOS, right Android:
![Снимок экрана 2020-07-24 в 15 51 38](https://user-images.githubusercontent.com/9552501/88393224-f4f26880-cdc5-11ea-81d1-e9247239c695.png)

Style Cancel button:
![Снимок экрана 2020-07-24 в 15 53 21](https://user-images.githubusercontent.com/9552501/88393298-13586400-cdc6-11ea-9333-bc728d11170c.png)

Style Save button:
![Снимок экрана 2020-07-24 в 15 53 29](https://user-images.githubusercontent.com/9552501/88393317-1a7f7200-cdc6-11ea-8761-3a9fce19a7b0.png)

**Comment by Dorofeev** [comment]
For iOS constraints you should use `root.safeArea` when add constraint to screen border. Because of [Safe Area Layout Guide](https://medium.com/@hassanahmedkhan/playing-it-safe-with-safe-area-layout-guide-b3f09bdc71fe)

**Comment by Diy2210** [comment]
> For iOS constraints you should use `root.safeArea` when add constraint to screen border. Because of [Safe Area Layout Guide](https://medium.com/@hassanahmedkhan/playing-it-safe-with-safe-area-layout-guide-b3f09bdc71fe)

**Tnx!**
![Simulator Screen Shot - iPhone SE (2nd generation) - 2020-07-24 at 17 05 00](https://user-images.githubusercontent.com/9552501/88399670-e741e080-cdcf-11ea-9eb6-e6f44f13e90d.png)

**Comment by Diy2210** [comment]
And how about button style?

**Comment by Alex009** [comment]
@Diy2210 on android button have default paddings, but on ios button not have default paddings. you can set own paddings in viewFactory

**Comment by Diy2210** [comment]
> @Diy2210 on android button have default paddings, but on ios button not have default paddings. you can set own paddings in viewFactory

**Ok, tnx!**
