### ISSUE TITLE
Update to Kotlin 1.4

### ISSUE THREAD

**Issue by Alex009** [icerockdev/moko-widgets#284]

**Comment by stevesoltys** [comment]
To save you some time debugging, I found that 1.4.10 contains a bug that affects this project: https://youtrack.jetbrains.com/issue/KT-43040

This does have a hotfix though, which can be found in the comments 😄

**Comment by Alex009** [comment]
@stevesoltys big thanks :)

**Comment by Alex009** [comment]
updated to Kotlin 1.4.30-M1 in 2cacf9a
