### ISSUE TITLE
Input widget with right action button

### ISSUE THREAD

**Issue by kovalandrew** [icerockdev/moko-widgets#57]
Need widget with customisation of right action button and its action
<img width="725" alt="Снимок экрана 2020-02-03 в 17 58 53" src="https://user-images.githubusercontent.com/11803725/73647979-2dcf4180-46af-11ea-8d28-43a2c51b1061.png">

**Comment by Alex009** [comment]
i suggest just use composition of exist widgets. In root is `constraint`, childs is `input` and `button`. For `input` set padding right, and `button` set centerY to `input`, rightToRight to `input`
