### ISSUE TITLE
StringResource as routing argument for screens

### ISSUE THREAD

**Issue by Tetraquark** [icerockdev/moko-widgets#72]
There is need to transfer `StringResource` or at least `StringDesc` objects between screens using routing arguments. But the problem is that the classes don't inherit from `Parcelable`, so they can't be placed into `Intent` for the Android platform. So, we need to find a way to implement this feature.

**Comment by Alex009** [comment]
started from moko-resources 0.8.0 you can use in Parcelable containers this classes:
```
@Parcelize
data class Args(
    val stringResource: StringResource,
    val fontResource: FontResource,
    val imageResource: ImageResource,
    val pluralsResource: PluralsResource,
    val stringDescRaw: StringDesc.Raw,
    val stringDescStringResource: StringResource,
    val stringDescPluralsResource: PluralsResource
) : Parcelable
```
