### ISSUE TITLE
Add InputType for one time code with availability past code from sms 

### ISSUE THREAD

**Issue by Dorofeev** [icerockdev/moko-widgets#74]
Like on screenshot
![EKegK8ZUwAA2xP0](https://user-images.githubusercontent.com/701307/74003582-b4349d80-49a5-11ea-9002-2749e5b744ff.jpg)

**Comment by Lobynya** [comment]
for Android use the SMS User Consent API
https://developers.google.com/identity/sms-retriever/user-consent/request
create and register BroadcastReceiver in widget, get message in onActivityResult

**Comment by Alex009** [comment]
merged
