### ISSUE TITLE
System Navbar customisation

### ISSUE THREAD

**Issue by Anafemest** [icerockdev/moko-widgets#9]
min. requirements:

background (bg color),
text customisation (size, color)
left icon customisation (margin, resource)
right icon support and customisation (margin, resource)

maybe immediately add customisation status bar? (light/dark + bg color and opacity)

**Comment by Alex009** [comment]
- text font customization +1
- background color customization +1
- back icon customization +1

**Comment by Alex009** [comment]
also need onBackButtonPressed callback (if not set - used default logic. if set - used custom logic)

**Comment by Alex009** [comment]
API of common code:
```
sealed class NavigationBar {
    object None : NavigationBar()
    data class Normal(
        val title: StringDesc,
        val styles: Styles? = null,
        val backButton: BarButton? = null,
        val actions: List<BarButton>? = null
    ) : NavigationBar() {

        data class Styles(
            val backgroundColor: Color? = null,
            val textStyle: TextStyle? = null,
            val tintColor: Color? = null
        )

        data class BarButton(
            val icon: ImageResource,
            val action: () -> Unit
        )
    }
}
```

**Comment by Alex009** [comment]
merged
