### ISSUE TITLE
Add date/time picker dialog

### ISSUE THREAD

**Issue by Lobynya** [icerockdev/moko-widgets#90]
separate date and time in 12 hour format selection modes 
set min/max selected date
set color for background title, title, buttons, selected date, current date

![3 3 3 Sign Up](https://user-images.githubusercontent.com/26733767/74924153-8a975f80-5404-11ea-818c-c12ac29c67aa.png)
![date picker](https://user-images.githubusercontent.com/26733767/74307391-baf15500-4d97-11ea-97ca-d6b7aaa55a98.png)

**Comment by Alex009** [comment]
merged
