### ISSUE TITLE
isKeyboardResizeContent not working in some case 

### ISSUE THREAD

**Issue by Dorofeev** [icerockdev/moko-widgets#94]
There is full code of screen on which isKeyboardResizeContent not working.
But after route to next screen and back to this screen, it start resizing content properly.

    override val isDismissKeyboardOnTap: Boolean = true
    override val isKeyboardResizeContent: Boolean = true

    override fun createContentWidget() = with(theme) {

        val viewModel = getViewModel {
            createViewModel(createEventsDispatcher())
        }

        viewModel.eventsDispatcher.listen(this@RestorePassPhoneScreen, this@RestorePassPhoneScreen)

        constraint(size = WidgetSize.AsParent) {
            val phone = +input(
                size = WidgetSize.Const(SizeSpec.MatchConstraint, SizeSpec.WrapContent),
                id = Ids.PhoneInput,
                label = const(strings.phone),
                field = viewModel.phoneField,
                inputType = InputType.PHONE
            )
            val next = +button(
                category = styles.nextButtonCategry,
                size = WidgetSize.Const(SizeSpec.MatchConstraint, SizeSpec.Exact(50f)),
                id = Ids.NextButton,
                content = ButtonWidget.Content.Text(Value.data(strings.next)),
                onTap = {
                    viewModel.onNext()
                }
            )
            constraints {
                phone topToTop root.safeArea offset 24
                phone leftRightToLeftRight root.safeArea offset 16

                next bottomToBottom root.safeArea offset 16
                next leftRightToLeftRight root.safeArea offset 16
            }
        }
    }

    override fun routeToConfirmCode(phone: String, token: String) {
        confirmCodeRoute.route(Pair(token, phone))
    }

    override fun showError(error: StringDesc) {
        showToast(error)
    }

    object Ids {
        object PhoneInput : InputWidget.Id
        object NextButton : ButtonWidget.Id
    }

    class Styles(
        val nextButtonCategry: ButtonWidget.Category?
    )

**Comment by Alex009** [comment]
merged
