### ISSUE TITLE
Unwanted tint color for icons of ButtonWithIconViewFactory

### ISSUE THREAD

**Issue by Tetraquark** [icerockdev/moko-widgets#95]
It looks like icons of buttons have excess tint color on both platforms that were builded with ButtonWithIconViewFactory.

Android:
![android_1](https://user-images.githubusercontent.com/7954933/74402912-31558c00-4e58-11ea-95a1-67730a4877ee.png)

iOS:
![ios](https://user-images.githubusercontent.com/7954933/74402927-39adc700-4e58-11ea-84f5-5d586cfddb91.png)

It can be fixed by disabling tint for the android factory:

```kotlin
button.iconTint = null
```

And by changing `buttonType` for the iOS factory:

```kotlin
buttonType = UIButtonTypeCustom
```

**Comment by Alex009** [comment]
merged
