### ISSUE TITLE
showToast on android can throw IllegalStateException: not attached to a context

### ISSUE THREAD

**Issue by Lobynya** [icerockdev/moko-widgets#97]
When Screen try show toast when it alredy not attached to a context, requireContext throw IllegalStateException

**Comment by Lobynya** [comment]
EventDispatcher get event before Fragment call onPause
but executor start block after Fragment was detach from Activity

59.292 19935-19935/com.alliancetrucks.app.debug I/EventsDispatcher: connectListener  
07.297 19935-19935/com.alliancetrucks.app.debug I/EventsDispatcher: event listener not null
07.301 19935-19935/com.alliancetrucks.app.debug I/EventsDispatcher: disconnectListener 
07.319 19935-19935/com.alliancetrucks.app.debug I/EventsDispatcher: onDestroyed       
07.448 19935-19935/com.alliancetrucks.app.debug I/EventsDispatcher: connectListener   
07.497 19935-19935/com.alliancetrucks.app.debug I/EventsDispatcher: executor.execute     
07.498 19935-19935/com.alliancetrucks.app.debug I/EventsDispatcher: block start
07.498 19935-19935/com.alliancetrucks.app.debug I/EventsDispatcher: Screen try show error

**Comment by Alex009** [comment]
merged
